//! This module contains the GDObject struct, used for parsing to/from raw object strings
//! This module also contains the GDObjConfig metadata descriptor struct for GDObjects
use std::fmt::{Debug, Display, Write};

use crate::cclocallevels::{
    gdobj::{
        ids::properties::*,
        meta::{GDObjAttributes, GDObjConfig},
        structs::{
            ColourChannel, Event,
            GDObjPropType::{self},
            GDValue, Group, ZLayer,
        },
    },
    properties::{self, OBJECT_NAMES, get_obj_property_type},
};

pub mod defaults;
/// This file contains all supported block ids and property ids.
/// This file is autogenerated by the build script.
pub mod ids {
    #![allow(missing_docs)]
    include!(concat!(env!("OUT_DIR"), "/ids.rs"));
}
pub mod constructors;
pub mod meta;
pub mod structs;

macro_rules! parse {
    ($v:expr => $t:ty) => {
        $v.parse::<$t>().unwrap_or_default()
    };
}

/// An in-game object in GD. This struct covers all objects placable in the editor. It is divided into three fields: the ID (object id, which is necessary to tell what an object is),
/// general properties - which are common properties that every object has (e.g. position, rotation), and object-specific properties (in the `properties` field).
#[derive(Clone, PartialEq)]
#[must_use]
pub struct GDObject {
    /// The object's ID. here: [Map of object IDs to names here](crate::cclocallevels::properties::OBJECT_NAMES), [Object ID consts here](ids::objects).
    pub id: i32,
    /// General properties, such as position and scale.
    pub config: GDObjConfig,
    /// Object-specific properties
    pub properties: Vec<(u16, GDValue)>,
}

impl Display for GDObject {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let mut group_str = String::new();
        if !self.config.groups.is_empty() {
            group_str += " with groups: ";
            for (idx, g) in self.config.groups.iter().enumerate() {
                if idx != 0 {
                    group_str.push_str(", ");
                }
                let _ = write!(group_str, "{}", g.id());
            }
        }

        let mut trigger_conf_str = String::new();
        if self.config.trigger_cfg.spawnable || self.config.trigger_cfg.touchable {
            if self.config.trigger_cfg.multitriggerable {
                trigger_conf_str += "Multi";
            }
            if self.config.trigger_cfg.touchable {
                trigger_conf_str += "touchable ";
            } else if self.config.trigger_cfg.spawnable {
                trigger_conf_str += "spawnable ";
            }
        }

        write!(
            f,
            "{trigger_conf_str}{} @ ({}, {}) scaled to ({}, {}){} angled to {}°",
            self.get_name(),
            self.config.pos.0,
            self.config.pos.1,
            self.config.scale.0,
            self.config.scale.1,
            group_str,
            self.config.angle
        )
    }
}

impl Debug for GDObject {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let mut property_str = String::with_capacity(self.properties.len() * 32);

        for (property, value) in &self.properties {
            let desc = properties::PROPERTY_TABLE.get(property).map(|p| p.0);
            if let Some(d) = desc {
                write!(property_str, "\n    - {d}: {value:?}")
            } else {
                write!(property_str, "\n    - {property}: {value:?}")
            }
            .unwrap();
        }

        write!(
            f,
            "{} with properties:{property_str}",
            <Self as ToString>::to_string(self),
        )
    }
}

const KA_PROPERTY_OFFSET: u16 = 10_000;

impl GDObject {
    /// Parses raw object string to `GDObject`
    pub fn parse_str<T: AsRef<str>>(s: T) -> GDObject {
        let s = s.as_ref();
        let mut obj = GDObject {
            id: 1,
            config: GDObjConfig::default(),
            properties: vec![],
        };

        let mut iter = s.trim_end_matches(';').split(',');
        while let (Some(idx), Some(val)) = (iter.next(), iter.next()) {
            let idx_u16 = match idx.parse::<u16>() {
                Ok(n) => n,
                Err(_) => match idx[2..].parse::<u16>() {
                    Ok(n) => n + KA_PROPERTY_OFFSET,
                    Err(_) => 65535,
                },
            };

            match idx_u16 {
                OBJECT_ID => obj.id = parse!(val => i32),
                X_POS => obj.config.pos.0 = val.parse().unwrap_or(0.0),
                Y_POS => obj.config.pos.1 = val.parse().unwrap_or(0.0),
                ROTATION => obj.config.angle = val.parse().unwrap_or(0.0),
                TOUCH_TRIGGERABLE => obj.config.trigger_cfg.touchable = parse!(val => bool),
                SPAWN_TRIGGERABLE => obj.config.trigger_cfg.spawnable = parse!(val => bool),
                MULTITRIGGERABLE => obj.config.trigger_cfg.multitriggerable = parse!(val => bool),
                GROUPS => {
                    obj.config.add_groups(
                        val.trim_matches('"')
                            .split('.')
                            .filter_map(|g| g.parse::<i16>().ok())
                            .map(Group::Regular)
                            .collect::<Vec<Group>>(),
                    );
                }
                X_SCALE => obj.config.scale.0 = val.parse().unwrap_or(1.0),
                Y_SCALE => obj.config.scale.1 = val.parse().unwrap_or(1.0),
                EDITOR_LAYER_1 => obj.config.editor_layers.0 = parse!(val => i16),
                EDITOR_LAYER_2 => obj.config.editor_layers.1 = parse!(val => i16),
                OBJECT_COLOUR => {
                    obj.config.colour_channels.0 = ColourChannel::from(parse!(val => i16));
                }
                SECONDARY_COLOUR => {
                    obj.config.colour_channels.1 = ColourChannel::from(parse!(val => i16));
                }
                Z_LAYER => obj.config.z_layer = ZLayer::from(parse!(val => i32)),
                Z_ORDER => obj.config.z_order = parse!(val => i32),
                ENTER_EFFECT_CHANNEL => obj.config.enter_effect_channel = parse!(val => i16),
                OBJECT_MATERIAL => obj.config.material_id = parse!(val => i16),
                DONT_FADE => obj
                    .config
                    .attributes
                    .set(GDObjAttributes::dont_fade, parse!(val => bool)),
                DONT_ENTER => obj
                    .config
                    .attributes
                    .set(GDObjAttributes::dont_enter, parse!(val => bool)),
                NO_OBJECT_EFFECTS => obj
                    .config
                    .attributes
                    .set(GDObjAttributes::no_effects, parse!(val => bool)),
                IS_GROUP_PARENT => obj
                    .config
                    .attributes
                    .set(GDObjAttributes::is_group_parent, parse!(val => bool)),
                IS_AREA_PARENT => obj
                    .config
                    .attributes
                    .set(GDObjAttributes::is_area_parent, parse!(val => bool)),
                DONT_BOOST_X => obj
                    .config
                    .attributes
                    .set(GDObjAttributes::dont_boost_x, parse!(val => bool)),
                DONT_BOOST_Y => obj
                    .config
                    .attributes
                    .set(GDObjAttributes::dont_boost_y, parse!(val => bool)),
                IS_HIGH_DETAIL => obj
                    .config
                    .attributes
                    .set(GDObjAttributes::high_detail, parse!(val => bool)),
                NO_TOUCH => obj
                    .config
                    .attributes
                    .set(GDObjAttributes::no_touch, parse!(val => bool)),
                PASSABLE => obj
                    .config
                    .attributes
                    .set(GDObjAttributes::passable, parse!(val => bool)),
                HIDDEN => obj
                    .config
                    .attributes
                    .set(GDObjAttributes::hidden, parse!(val => bool)),
                NONSTICK_X => obj
                    .config
                    .attributes
                    .set(GDObjAttributes::non_stick_x, parse!(val => bool)),
                NONSTICK_Y => obj
                    .config
                    .attributes
                    .set(GDObjAttributes::non_stick_y, parse!(val => bool)),
                EXTRA_STICKY => obj
                    .config
                    .attributes
                    .set(GDObjAttributes::extra_sticky, parse!(val => bool)),
                HAS_EXTENDED_COLLISION => obj
                    .config
                    .attributes
                    .set(GDObjAttributes::extended_collision, parse!(val => bool)),
                IS_ICE_BLOCK => obj
                    .config
                    .attributes
                    .set(GDObjAttributes::is_ice_block, parse!(val => bool)),
                GRIP_SLOPE => obj
                    .config
                    .attributes
                    .set(GDObjAttributes::grip_slope, parse!(val => bool)),
                NO_GLOW => obj
                    .config
                    .attributes
                    .set(GDObjAttributes::no_glow, parse!(val => bool)),
                NO_PARTICLES => obj
                    .config
                    .attributes
                    .set(GDObjAttributes::no_particles, parse!(val => bool)),
                SCALE_STICK => obj
                    .config
                    .attributes
                    .set(GDObjAttributes::scale_stick, parse!(val => bool)),
                NO_AUDIO_SCALE => obj
                    .config
                    .attributes
                    .set(GDObjAttributes::no_audio_scale, parse!(val => bool)),
                SINGLE_PLAYER_TOUCH => obj
                    .config
                    .attributes
                    .set(GDObjAttributes::single_ptouch, parse!(val => bool)),
                CENTER_EFFECT => obj
                    .config
                    .attributes
                    .set(GDObjAttributes::center_effect, parse!(val => bool)),
                REVERSES_GAMEPLAY => obj
                    .config
                    .attributes
                    .set(GDObjAttributes::reverse, parse!(val => bool)),
                MATERIAL_CONTROL_ID => obj.config.control_id = parse!(val => i16),
                PARENT_GROUPS => {
                    // add groups method handles deduping
                    obj.config.add_groups(
                        val.trim_matches('"')
                            .split('.')
                            .filter_map(|g| g.parse::<i16>().ok())
                            .map(Group::Parent)
                            .collect::<Vec<Group>>(),
                    );
                }
                n => obj.set_property_raw(n, val),
            }
        }

        obj
    }

    fn set_property_raw(&mut self, p: u16, value: &str) {
        self.set_property(
            p,
            GDValue::from(
                get_obj_property_type(p).unwrap_or(GDObjPropType::Unknown),
                value,
            ),
        );
    }

    /// Sets the prpoerty ID to the value, and craetes it if it doesn't exist
    pub fn set_property(&mut self, p: u16, val: GDValue) {
        match self.properties.binary_search_by_key(&p, |t| t.0) {
            Ok(idx) => self.properties[idx].1 = val,
            Err(idx) => self.properties.insert(idx, (p, val)),
        }
    }

    /// Removes the property from this object's property map by its ID.
    pub fn del_property(&mut self, p: u16) {
        if let Ok(idx) = self.properties.binary_search_by_key(&p, |t| t.0) {
            let _ = self.properties.remove(idx);
        }
    }

    /// Returns this object as a property string. This function does not preserve the order of properties as they
    /// originally were in the object since property order does not matter because they are collectively treated as
    /// part of a dictionary of properties for this object. Each property is serialized as follows:
    /// * The id of this object (property ID 1) is serialized at the beginning of the string.
    /// * Each property covered in [`GDObjConfig`] is serialized with [`GDObjConfig::serialise_to_string`].
    /// * Each remaining property's value is serialized by `GDValue`'s implementation of Display.
    ///
    /// Each object string is guaranteed to end with a `;`, meaning that to encode multiple objects, it is recommended
    /// to simply call this function and join them without any delimeter, which is what the [`serialise_objects`] function does.
    #[must_use]
    pub fn serialise_to_string(&self) -> String {
        // the average length of a property is assumed to be 8 bytes - an estimate.
        let mut properties_string = String::with_capacity(self.properties.len() * 8);
        for (idx, val) in &self.properties {
            // `GDValue` implementation for `Display` handles serialization.
            if *idx < KA_PROPERTY_OFFSET {
                write!(properties_string, ",{idx},{val}").unwrap();
            } else {
                write!(properties_string, ",kA{},{val}", idx - KA_PROPERTY_OFFSET).unwrap();
            }
        }
        let config_str = self.config.serialise_to_string();

        format!("1,{}{config_str}{properties_string};", self.id)
    }

    /// Returns this object's name if it was defined in [`crate::cclocallevels::properties::OBJECT_NAMES`], otherwise returns "Object {id}"
    #[inline]
    #[must_use]
    pub fn get_name(&self) -> String {
        OBJECT_NAMES
            .iter()
            .find(|&o| o.0 == self.id)
            .unwrap_or(&(0, format!("Object {}", self.id).as_str()))
            .1
            .to_string()
    }

    /// Default constructor for this object.
    #[inline]
    pub fn new(id: i32, config: &GDObjConfig, properties: Vec<(u16, GDValue)>) -> Self {
        GDObject {
            id,
            config: config.clone(),
            properties,
        }
    }

    #[inline]
    /// Creates a default object from the specified ID. Internally calls [`defaults::default_object`].
    pub fn default_from_id(id: i32) -> Self {
        defaults::default_object(id)
    }

    #[inline]
    fn get_attr_as_gdvalue(&self, attr: GDObjAttributes) -> GDValue {
        GDValue::Bool(self.config.get_attribute_flag(attr))
    }

    /// Fetches a property from this object's configuration
    pub fn get_property(&self, p: u16) -> Option<GDValue> {
        match p {
            // one of the most fascinating matches of all time
            1 => Some(GDValue::Int(self.id)),
            2 => Some(GDValue::Float(self.config.pos.0)),
            3 => Some(GDValue::Float(self.config.pos.1)),
            6 => Some(GDValue::Float(self.config.angle)),
            11 => Some(GDValue::Bool(self.config.trigger_cfg.touchable)),
            57 => Some(GDValue::from_group_list(&self.config.groups)),
            62 => Some(GDValue::Bool(self.config.trigger_cfg.spawnable)),
            87 => Some(GDValue::Bool(self.config.trigger_cfg.multitriggerable)),
            128 => Some(GDValue::Float(self.config.scale.0)),
            129 => Some(GDValue::Float(self.config.scale.1)),
            20 => Some(GDValue::Short(self.config.editor_layers.0)),
            61 => Some(GDValue::Short(self.config.editor_layers.1)),
            21 => Some(GDValue::ColourChannel(self.config.colour_channels.0)),
            22 => Some(GDValue::ColourChannel(self.config.colour_channels.1)),
            24 => Some(GDValue::ZLayer(self.config.z_layer)),
            25 => Some(GDValue::Int(self.config.z_order)),
            343 => Some(GDValue::Short(self.config.enter_effect_channel)),
            446 => Some(GDValue::Short(self.config.material_id)),
            534 => Some(GDValue::Short(self.config.control_id)),
            64 => Some(self.get_attr_as_gdvalue(GDObjAttributes::dont_fade)),
            67 => Some(self.get_attr_as_gdvalue(GDObjAttributes::dont_enter)),
            116 => Some(self.get_attr_as_gdvalue(GDObjAttributes::no_effects)),
            34 => Some(self.get_attr_as_gdvalue(GDObjAttributes::is_group_parent)),
            279 => Some(self.get_attr_as_gdvalue(GDObjAttributes::is_area_parent)),
            509 => Some(self.get_attr_as_gdvalue(GDObjAttributes::dont_boost_x)),
            496 => Some(self.get_attr_as_gdvalue(GDObjAttributes::dont_boost_y)),
            103 => Some(self.get_attr_as_gdvalue(GDObjAttributes::high_detail)),
            121 => Some(self.get_attr_as_gdvalue(GDObjAttributes::no_touch)),
            134 => Some(self.get_attr_as_gdvalue(GDObjAttributes::passable)),
            135 => Some(self.get_attr_as_gdvalue(GDObjAttributes::hidden)),
            136 => Some(self.get_attr_as_gdvalue(GDObjAttributes::non_stick_x)),
            289 => Some(self.get_attr_as_gdvalue(GDObjAttributes::non_stick_y)),
            495 => Some(self.get_attr_as_gdvalue(GDObjAttributes::extra_sticky)),
            511 => Some(self.get_attr_as_gdvalue(GDObjAttributes::extended_collision)),
            137 => Some(self.get_attr_as_gdvalue(GDObjAttributes::is_ice_block)),
            193 => Some(self.get_attr_as_gdvalue(GDObjAttributes::grip_slope)),
            96 => Some(self.get_attr_as_gdvalue(GDObjAttributes::no_glow)),
            507 => Some(self.get_attr_as_gdvalue(GDObjAttributes::no_particles)),
            356 => Some(self.get_attr_as_gdvalue(GDObjAttributes::scale_stick)),
            372 => Some(self.get_attr_as_gdvalue(GDObjAttributes::no_audio_scale)),
            284 => Some(self.get_attr_as_gdvalue(GDObjAttributes::single_ptouch)),
            369 => Some(self.get_attr_as_gdvalue(GDObjAttributes::center_effect)),
            117 => Some(self.get_attr_as_gdvalue(GDObjAttributes::reverse)),

            _ => self
                .properties
                .binary_search_by_key(&p, |(key, _)| *key)
                .ok()
                .map(|idx| self.properties[idx].1.clone()),
        }
    }

    /// Returns `true` if this object has as a set property at index `p`. If this function returns `true` for a given `p`, then `GDObject::get_property` is guaranteed to return a `Some`.
    pub fn has_property(&self, p: u16) -> bool {
        match p {
            // all of the below are intrinsic properties of an object that are either set or filled in with a default value (by GD) if left unset.
            1 | 2 | 3 | 6 | 11 | 57 | 62 | 87 | 128 | 129 | 20 | 61 | 21 | 22 | 24 | 25 | 343
            | 446 | 534 => true,
            64 => self.config.get_attribute_flag(GDObjAttributes::dont_fade),
            67 => self.config.get_attribute_flag(GDObjAttributes::dont_enter),
            116 => self.config.get_attribute_flag(GDObjAttributes::no_effects),
            34 => self
                .config
                .get_attribute_flag(GDObjAttributes::is_group_parent),
            279 => self
                .config
                .get_attribute_flag(GDObjAttributes::is_area_parent),
            509 => self
                .config
                .get_attribute_flag(GDObjAttributes::dont_boost_x),
            496 => self
                .config
                .get_attribute_flag(GDObjAttributes::dont_boost_y),
            103 => self.config.get_attribute_flag(GDObjAttributes::high_detail),
            121 => self.config.get_attribute_flag(GDObjAttributes::no_touch),
            134 => self.config.get_attribute_flag(GDObjAttributes::passable),
            135 => self.config.get_attribute_flag(GDObjAttributes::hidden),
            136 => self.config.get_attribute_flag(GDObjAttributes::non_stick_x),
            289 => self.config.get_attribute_flag(GDObjAttributes::non_stick_y),
            495 => self
                .config
                .get_attribute_flag(GDObjAttributes::extra_sticky),
            511 => self
                .config
                .get_attribute_flag(GDObjAttributes::extended_collision),
            137 => self
                .config
                .get_attribute_flag(GDObjAttributes::is_ice_block),
            193 => self.config.get_attribute_flag(GDObjAttributes::grip_slope),
            96 => self.config.get_attribute_flag(GDObjAttributes::no_glow),
            507 => self
                .config
                .get_attribute_flag(GDObjAttributes::no_particles),
            356 => self.config.get_attribute_flag(GDObjAttributes::scale_stick),
            372 => self
                .config
                .get_attribute_flag(GDObjAttributes::no_audio_scale),
            284 => self
                .config
                .get_attribute_flag(GDObjAttributes::single_ptouch),
            369 => self
                .config
                .get_attribute_flag(GDObjAttributes::center_effect),
            117 => self.config.get_attribute_flag(GDObjAttributes::reverse),

            _ => self
                .properties
                .binary_search_by_key(&p, |(key, _)| *key)
                .is_ok(),
        }
    }

    /// Set this object's internal config
    pub fn set_config(&mut self, config: GDObjConfig) {
        self.config = config;
    }

    /// Creates an object from a property descriptor object. This is the standard way to create objects with extra properties such as triggers.
    pub fn from_config<P: ObjectProperties>(config: GDObjConfig, details: P) -> Self {
        Self {
            id: details.object_id(),
            config,
            properties: details.serialise(),
        }
    }
}

/// Returns the objects in the iterator as a string.
pub fn serialise_objects<I: IntoIterator<Item = GDObject>>(objects: I) -> String {
    objects
        .into_iter()
        .map(|obj| obj.serialise_to_string())
        .collect::<String>() // concats all strings
}

/// Trait for structs that encode configuration for a GD object. This trait is used in [`GDObject::from_config`].
///
/// Structs that implement this trait cannot be treated as or directly converted into `GDValue` since this trait lacks a definition for an object configuration function -
/// specifically one that returns [`GDObjConfig`] - because this trait is intended to encode only the properties specific to one object. Of course, it is trivial to convert
/// any struct that implements this trait if you also have a `GDObjConfig`, which is exactly what [`GDObject::from_config`] does.
pub trait ObjectProperties {
    /// Serialise this object to a list of properties in the form of tuples: (id, value)
    fn serialise(&self) -> Vec<(u16, GDValue)>;
    /// Returns the object ID that this struct is configured for.
    fn object_id(&self) -> i32;
    /// Converts a `GDobject` to this struct. Should fail if the object ID doesn't match and if the required values aren't of the right type.
    /// Values that are missing from the original object (usually due to being unset) should be filled in with their type's implementation of `Default`.
    /// For GD-specific types, such as [`structs::Speed`], the `Default` implementation will be whatever is the regular default value when a trigger is placed in the game.
    #[allow(unused_variables)]
    fn from_object(obj: &GDObject) -> Option<Self>
    where
        Self: Sized,
    {
        None
    }
}

macro_rules! prop_value {
    // This arm should not exist because there is a GDValue variant for every type - except for two.
    // RobTop uses property 88 to enconde both `PickupTriggerMode` and `InstantCountComparison`, which are two different enums whose variant correspond to different things.
    // This macro is primarily used in the `object_descriptor`, which automatically creates both the desrialization and serialization of objects.
    // If a variant were created for either type in GDValue, it would cause the other one, which is not implemented, to be incorrectly parsed as the implemented one, which may cause confusion.
    // As a result, I have opted to leave this arm in specifically for those two fields.
    //
    // Note: **DO NOT** use this for any other field, unless it is bound to a property that also has a conflicting type situation.
    (as_i32, $field:expr) => {
        GDValue::Int($field as i32)
    };
    (to_i32, $field:expr) => {
        GDValue::Int($field.to_num())
    };
    (Events, $field:expr) => {
        GDValue::Events($field.clone())
    };
    (ProbabilitiesList, $field:expr) => {
        GDValue::from_prob_list($field.clone())
    };
    (Remaps, $field:expr) => {
        GDValue::from_spawn_remaps($field.clone())
    };
    ($t:ident, $field:expr) => {
        GDValue::$t($field)
    };
}

// GDValue => field type conversion
macro_rules! from_obj_value {
    (Events, $field:expr) => {
        $field.into()
    };
    (ProbabilitiesList, $field:expr) => {
        $field.into_vec()
    };
    (Remaps, $field:expr) => {
        $field.into_vec()
    };
    ($t:ident, $field:expr) => {
        $field.into()
    };
}

macro_rules! object_field_match {
    (to_i32, $field_type:ty, $p:ident) => {
        match $p {
            GDValue::Int(l) => <$field_type>::from(l),
            _ => return None,
        }
    };
    (as_i32, $field_type:ty, $p:ident) => {
        match $p {
            GDValue::Int(l) => match <$field_type>::try_from(l) {
                Ok(v) => v,
                Err(_) => return None,
            },
            _ => return None,
        }
    };
    (Remaps, $field_type:ty, $p:ident) => {
        match $p {
            // GDValue::Int(l) => l
            GDValue::SpawnRemapsList(l) => {
                crate::cclocallevels::gdobj::from_obj_value!(Remaps, l)
            }
            _ => return None,
        }
    };
    ($gd_type:ident, $field_type:ty, $p:ident) => {
        match $p {
            // GDValue::Int(l) => l
            GDValue::$gd_type(l) => crate::cclocallevels::gdobj::from_obj_value!($gd_type, l),
            _ => return None,
        }
    };
}

// quick way to create object descriptors where the descriptor can be serialised as a list of its properties
macro_rules! object_descriptor {
    ($(#[$meta:meta])* $descriptor:ident: $object:expr => { $( $(#[$fmeta:meta])* $field:ident : $ftype:ty => $prop_t:ident $prop_id:expr ),* $(,)? }) => {
        #[derive(Debug, Clone, PartialEq, Default)]
        #[allow(missing_docs)]
        $(#[$meta])*
        pub struct $descriptor {
            $(
                $(#[$fmeta])*
                pub $field: $ftype,
            )*
        }

        impl ObjectProperties for $descriptor {
            fn serialise(&self) -> Vec<(u16, GDValue)> {
                vec![
                    $(
                        ($prop_id, crate::cclocallevels::gdobj::prop_value!($prop_t, self.$field)),
                    )*
                ]
            }

            fn object_id(&self) -> i32 {
                $object
            }

            fn from_object(obj: &GDObject) -> Option<Self> {
                if obj.id == $object {
                    return None;
                }

                let mut this = Self::default();

                $(
                    // here, try to assign each field the value from the object
                    if let Some(p) = obj.get_property($prop_id) {
                        // field exists, try to parse it. return None if you get bad data.
                        this.$field = crate::cclocallevels::gdobj::object_field_match!($prop_t, $ftype, p)
                    };
                )*

                return Some(this);
            }
        }
    };
}

pub(crate) use from_obj_value;
pub(crate) use object_descriptor;
pub(crate) use object_field_match;
pub(crate) use prop_value;
